# Generated by Django 5.0.3 on 2024-05-23 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(max_length=200)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DersTalepleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('talep_notu', models.TextField(blank=True, max_length=200, null=True)),
                ('talep_durumu', models.BooleanField(default=False)),
                ('min_butce', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_butce', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('ogrenci_seviyesi', models.CharField(choices=[('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite'), ('yukseklisans', 'Yüksek Lisans')], max_length=50)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.ders')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('içerik', models.TextField(max_length=200)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alınan_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('gönderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gönderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_tipi', models.CharField(choices=[('egitmen', 'Eğitmen'), ('ogrenci', 'Öğrenci')], max_length=50)),
                ('bio', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('dogum_tarihi', models.DateField(blank=True, default='', null=True)),
                ('tel_no', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('kadin', 'Kadın')], max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye', models.CharField(choices=[('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite'), ('yukseklisans', 'Yüksek Lisans')], max_length=50)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EgitmenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='VerilebilecekDersler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saatlik_ucret', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.ders')),
                ('ders_dili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.dil')),
                ('egitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
