# Generated by Django 5.0.3 on 2024-05-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_profile_profil_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dogum_tarihi',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
