# Generated by Django 5.0.3 on 2024-05-21 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_bildirim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_tipi', models.CharField(choices=[('egitmen', 'Eğitmen'), ('ogrenci', 'Öğrenci')], max_length=50)),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('kadin', 'Kadın')], max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OgrenciProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye', models.CharField(choices=[('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite'), ('yukseklisans', 'Yüksek Lisans')], max_length=50)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EgitmenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Base.profile')),
            ],
        ),
    ]
