# Generated by Django 5.0.3 on 2024-05-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_alter_profile_dogum_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='verilendersler',
            name='ders_seviyesi',
            field=models.CharField(choices=[('İlkokul', 'İlkokul'), ('Ortaokul', 'Ortaokul'), ('Lise', 'Lise'), ('Universite', 'Üniversite'), ('Yukseklisans', 'Yüksek Lisans')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel_no',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verilendersler',
            name='sehir',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Base.sehir'),
            preserve_default=False,
        ),
    ]
