# Generated by Django 5.0.3 on 2024-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_profile_ogrenciprofile_egitmenprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='konum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
