# Generated by Django 5.0.3 on 2024-05-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_profile_konum'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
