# Generated by Django 5.0.6 on 2024-05-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_alter_mesaj_sohbet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='alici',
        ),
    ]
