# Generated by Django 5.0.3 on 2024-05-25 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_remove_mesaj_alici'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='alici',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alınan_mesajlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
