# Generated by Django 5.0.3 on 2024-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_mesaj_alici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='içerik',
            field=models.CharField(max_length=200),
        ),
    ]
