# Generated by Django 5.0.3 on 2024-05-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_alter_mesaj_içerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='derstalepleri',
            name='dil',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.dil'),
        ),
    ]
