# Generated by Django 5.0.3 on 2024-05-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_derstalepleri_dil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derstalepleri',
            name='dil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Base.dil'),
        ),
    ]
