# Generated by Django 5.0.3 on 2024-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_remove_profile_tel_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derstalepleri',
            name='ogrenci_seviyesi',
            field=models.CharField(choices=[('İlkokul', 'İlkokul'), ('Ortaokul', 'Ortaokul'), ('Lise', 'Lise'), ('Üniversite', 'Üniversite'), ('Yüksek Lisans', 'Yüksek Lisans')], max_length=50),
        ),
    ]
