# Generated by Django 4.2.11 on 2024-05-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Base", "0017_alter_derstalepleri_ogrenci_seviyesi"),
    ]

    operations = [
        migrations.DeleteModel(name="Bildirim",),
    ]
