# Generated by Django 4.2.11 on 2024-05-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Base", "0018_delete_bildirim"),
    ]

    operations = [
        migrations.RenameField(
            model_name="derstalepleri", old_name="isim", new_name="baslik",
        ),
        migrations.RemoveField(model_name="profile", name="dogum_tarihi",),
    ]
